# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b12150aad99e5e952ff4b37489632483163696b08e25a24154e1f9b526aaafa57c1618e83b6da780eefea887fb1dc07f28b188e252afdb0cd0b1f7caf94e7238

test:
  secret_key_base: 3490ba37a740d94259f2adb9acb2526a56f344b0101c464ac0c109d2abfe3154b45a7812998fdcdef987d2102c0aec83348540e1a84880dd7c87c4cd407b38de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
